# Generated by Django 4.2.6 on 2023-10-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='content',
            field=models.CharField(blank=True, null=True, verbose_name='本文'),
        ),
        migrations.AddField(
            model_name='diary',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真1'),
        ),
        migrations.AddField(
            model_name='diary',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真2'),
        ),
        migrations.AddField(
            model_name='diary',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真3'),
        ),
        migrations.AddField(
            model_name='diary',
            name='updateed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
    ]
